### ISSUE TITLE
Rendering pdb plot

### ISSUE THREAD

**Issue by stevemmarshall** [aws-samples/aws-batch-arch-for-protein-folding#2]
I get this error when trying to render a pdb plot... I assume it's because of an older version of jupyterlab running in Sagemaker?
[Open Browser Console for more detailed log - Double click to close this message]
Failed to load model class 'GridBoxModel' from module '@jupyter-widgets/controls'

**Comment by brianloyal** [comment]
Thanks for logging this, @stevemmarshall. Taking a look at it now. Was this from the SageMaker notebook instance that comes with the stack? Or a different python environment?

**Comment by stevemmarshall** [comment]
It was a sagemaker notebook and using the recommended kernel

**Comment by brianloyal** [comment]
Resolved in [v1.2.0](https://github.com/aws-samples/aws-batch-arch-for-protein-folding/releases/tag/v1.2.0)

**Comment by stevemmarshall** [comment]
Thanks Brian!
