### ISSUE TITLE
questions about pricing and multiple protein analysis

### ISSUE THREAD

**Issue by chongguo** [aws-samples/aws-batch-arch-for-protein-folding#6]
Hi I am profiling the speed of AF2 and I am seeing it regularly takes >1350s for a 32-amino acid long peptide, is this expected? Also is there s sample out there for running multiple proteins? Do they get batched when folding in AF2 or will they be running on different machines. I am trying to run ~10,000 at one time

**Comment by JoshB29** [comment]
The speed at which AlphaFold2 (or any of the other algorithms) runs will be dependent on a number of factors, include the underlying algorithm itself, and the instance type you run on. When submitting multiple jobs, they are not batched to run simultaneous on the same compute instance. Instead, AWS Batch will queue your runs and run them per your Batch cluster configurations. Your Batch cluster can be configured to run multiple jobs at the same time, but they will be run on separate machines in parallel. For large numbers of jobs, your jobs would be put on a queue, and Batch will run them as compute become available per your AWS Batch cluster [configurations](https://docs.aws.amazon.com/batch/latest/userguide/compute_environments.html).
